# Starter pipeline
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
    workingDirectory: 'cd C:\Users\jashw\eclipse-workspace\SeleniumBasicProgram2'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'https://github.com/jashwanthravuru/Demowebshop.git'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
